from pydantic import BaseModel
from typing import Optional

class Forex(BaseModel):
    TradeID: str
    TradeDate: str
    ValueDate: str
    TradeTime: str
    TraderID: str
    Counterparty: str
    CurrencyPair: str
    BuySell: str
    DealtCurrency: str
    BaseCurrency: str
    TermCurrency: str
    NotionalAmount: float
    FXRate: float
    TradeStatus: str
    SettlementStatus: str
    SettlementMethod: str
    Broker: str
    ExecutionVenue: str
    ProductType: str
    MaturityDate: str
    ConfirmationTimestamp: str
    SettlementDate: str
    BookingLocation: str
    Portfolio: str
    TradeVersion: Optional[int]
    CancellationFlag: str
    AmendmentFlag: str
    RiskSystemID: str
    RegulatoryReportingStatus: str
    TradeSourceSystem: str
    ConfirmationMethod: str
    ConfirmationStatus: str
    SettlementInstructions: str
    Custodian: str
    NettingEligibility: str
    TradeComplianceStatus: str
    KYCCheck: str
    SanctionsScreening: str
    ExceptionFlag: str
    ExceptionNotes: str
    AuditTrailRef: str
    CommissionAmount: float
    CommissionCurrency: str
    BrokerageFee: float
    BrokerageCurrency: str
    CustodyFee: float
    CustodyCurrency: str
    SettlementCost: float
    SettlementCurrency: str
    FXGainLoss: float
    PnlCalculated: float
    CostAllocationStatus: str
    CostCenter: str
    ExpenseApprovalStatus: str
    CostBookedDate: str