import json
import os

RULES_PATH = os.path.join(os.path.dirname(__file__), "forex_rules.json")

def load_forex_rules():
    if not os.path.exists(RULES_PATH):
        # Create a default rules file if it doesn't exist
        default_rules = {
			"ProductType": {"allowed": ["FORWARD", "SWAP", "SPOT"]},
            "BuySell": {"allowed": ["BUY", "SELL"]},
            "unique_trade_id": True
        }
        with open(RULES_PATH, "w") as f:
            json.dump(default_rules, f, indent=2)
    with open(RULES_PATH, "r") as f:
        return json.load(f)

forex_rules = load_forex_rules()

forex_schema = {
    "TradeID": str,
    "TradeDate": str,
    "ValueDate": str,
    "TradeTime": str,
    "TraderID": str,
    "Counterparty": str,
    "Counterparty ID": str,
    "LEI": str,
    "CurrencyPair": str,
    "BuySell": str,
    "DealtCurrency": str,
    "BaseCurrency": str,
    "TermCurrency": str,
    "NotionalAmount": float,
    "FXRate": float,
    "TradeStatus": str,
    "SettlementStatus": str,
    "SettlementMethod": str,
    "Broker": str,
    "ExecutionVenue": str,
    "ProductType": str,
    "MaturityDate": str,
    "ConfirmationTimestamp": str,
    "SettlementDate": str,
    "BookingLocation": str,
    "Portfolio": str,
    "TradeVersion": int,
    "CancellationFlag": str,
    "AmendmentFlag": str,
    "RiskSystemID": str,
    "RegulatoryReportingStatus": str,
    "TradeSourceSystem": str,
    "ConfirmationMethod": str,
    "ConfirmationStatus": str,
    "SettlementInstructions": str,
    "Custodian_Name": str,
    "NettingEligibility": str,
    "TradeComplianceStatus": str,
    "KYCCheck": str,
    "SanctionsScreening": str,
    "ExceptionFlag": str,
    "AuditTrailRef": str,
    "CommissionAmount": float,
    "CommissionCurrency": str,
    "BrokerageFee": float,
    "BrokerageCurrency": str,
    "CustodyFee": float,
    "CustodyCurrency": str,
    "SettlementCost": float,
    "SettlementCurrency": str,
    "FXGainLoss": float,
    "PnlCalculated": float,
    "CostAllocationStatus": str,
    "CostCenter": str,
    "ExpenseApprovalStatus": str,
    "CostBookedDate": str,
    "Exception Type": str,
    "Exception Description": str,
    "Exception Resolution": str,
    "Reporting Regulation": str,
    "Exception Reason": str,
    "Reporting Resolution": str,
    "RID": str,
    "ISIN": str,
    "Symbol": str,
    "Trading Venue": str,
    "Stock_Currency": str,
    "Country_of_Trade": str,
    "Instrument_Status": str,
    "ClientID_Equity": str,
    "KYC_Status_Equity": str,
    "Reference_Data_Validated": str,
    "Margin_Type": str,
    "Margin_Status": str,
    "Client_Approval_Status_Equity": str,
    "ClientID_Forex": str,
    "KYC_Status_Forex": str,
    "Expense_Approval_Status": str,
    "Client Approval Status(forex)": str,
    "Custodian_Ac_no": str,
    "Beneficiary_Client_ID": str,
    "Settlement_Cycle": str,
    "EffectiveDate_Equity": str,
    "ConfirmationStatus_Equity": str,
    "SWIFT_Equity": str,
    "BeneficiaryName_Equity": str,
    "Account_Number_Equity": str,
    "ABA_Equity": str,
    "BSB_Equity": str,
    "IBAN_Equity": str,
    "SORT_Equity": str,
    "Zengin_Equity": str,
    "Settlement_Method_Equity": str,
    "EffectiveDate_Forex": str,
    "ConfirmationStatus_Forex": str,
    "Account Number_Forex": str,
    "SWIFT_Forex": str,
    "BeneficiaryName_Forex": str,
    "ABA_Forex": str,
    "BSB_Forex": str,
    "IBAN_Forex": str,
    "SORT_Forex": str,
    "Zengin_Forex": str,
    "Settlement_Method_Forex": str,
}
